### ISSUE TITLE
(Android) GitJournal compatibility with Carbon

### ISSUE THREAD

**Issue by clach04** [kyoheiu/carbon#5]
1. Are you an Android user?
  2. Have you seen https://github.com/GitJournal/GitJournal
  3. Do they work well with each other?

**Comment by kyoheiu** [comment]
Yep I use an android phone. It seems GitJournal uses yaml header (which is relatively common in SSG I think), so if you'd like to use it and carbon together, I need to add the feature to parse the header and  display it. I'm not sure how many people actually want it, though.

EDIT: In addition, the structure where you store the data may matter. Assume you have the following structure:
```
data/
├─ test1.md
├─ test2.md
├─ test3.md
├─ child/
│  ├─ child1

```
Then you can probably access `.data/child/chidl1` in GItJournal,  but you can't in carbon, at least at the moment because it only handles single flat directory, not allowing users to use child directory inside `./data/*`.
This can be solved by changing the way carbon reads the data directory, though.

**Comment by clach04** [comment]
I've been playing with GitJournal for a little, I actually have disabled the front matter (yaml) support in GitJournal on my phone and it seems to work well (some minor issues), I need to make some time to play with Carbon then :-) This could be a nice solution for desktop.
